### ISSUE TITLE
Missing anchor

### ISSUE THREAD

**Issue by FredericDT** [BYRIO/byrteam#25]
![image](https://user-images.githubusercontent.com/16513314/45898417-8086c100-be0c-11e8-9eef-ac719c496a59.png)

As it designed, there should be an anchor

as well as

link to #groups

**Comment by dimpurr** [comment]
Maybe it should work now
If yes, you can close it

**Comment by FredericDT** [comment]
Test with Chrome 69

**Comment by FredericDT** [comment]
Worked with Firefox

**Comment by FredericDT** [comment]
Approve fixed by @dimpurr
