### ISSUE TITLE
BBS link is INCORRECT

### ISSUE THREAD

**Issue by FredericDT** [BYRIO/byrteam#28]
![image](https://user-images.githubusercontent.com/16513314/45900038-20464e00-be11-11e8-89a5-fed1687feefa.png)

**Comment by FredericDT** [comment]
It should be https://bbs.byr.cn

**Comment by dimpurr** [comment]
fixed

**Comment by FredericDT** [comment]
Approve fixed by https://github.com/BYRIO/byrteam/commit/f6ac090fff3c1d6794b2cc511d173a72d7496165
